# -*- coding: utf-8 -*-
"""compare_regions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IblyiN5d_HKMkVSH6hH4xbZHAWCdKmA-
"""

import cv2
import numpy as np

# ---------- STEP 1: Compute Absolute Difference ----------
def compute_absdiff(img1, img2):
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(gray1, gray2)
    _, thresh = cv2.threshold(diff, 30, 255, cv2.THRESH_BINARY)
    return thresh

# ---------- STEP 2: Get Contours of Changed Areas ----------
def get_contours(diff_img):
    contours, _ = cv2.findContours(diff_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    return contours

# ---------- STEP 3: Draw Highlighted Differences ----------
def draw_highlighted_differences(original_img, contours):
    overlay = np.zeros_like(original_img)
    cv2.drawContours(overlay, contours, -1, (0, 255, 0), thickness=cv2.FILLED)  # Filled green
    alpha = 0.4
    highlighted = cv2.addWeighted(overlay, alpha, original_img, 1 - alpha, 0)
    return highlighted

# ---------- STEP 4: Full Pipeline ----------
def visualize_image_difference(img1_path, img2_path):
    img1 = cv2.imread(img1_path)
    img2 = cv2.imread(img2_path)

    if img1 is None or img2 is None:
        print(f"❌ One or both images not found:\n{img1_path}\n{img2_path}")
        return

    if img1.shape != img2.shape:
        print("ℹ️ Resizing image2 to match image1...")
        img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))

    diff_thresh = compute_absdiff(img1, img2)
    contours = get_contours(diff_thresh)
    result_img = draw_highlighted_differences(img2, contours)

    # Display
    cv2.imshow("Image 1 (Reference)", img1)
    cv2.imshow("Image 2 (Compared)", img2)
    cv2.imshow("Difference Threshold", diff_thresh)
    cv2.imshow("Green Highlighted Differences", result_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# ---------- STEP 5: Run without choosing files ----------
image1_path = "a.png"  # Path to first image
image2_path = "b.png"  # Path to second image

visualize_image_difference(image1_path, image2_path)

